# coding: utf-8

"""
    PRIMECORE_PRIMECORE-WS

    API Definition of primecore

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.rogue_access_point_alarm_object_rogue_ap_alarm_details import RogueAccessPointAlarmObjectRogueApAlarmDetails


class TestRogueAccessPointAlarmObjectRogueApAlarmDetails(unittest.TestCase):
    """ RogueAccessPointAlarmObjectRogueApAlarmDetails unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRogueAccessPointAlarmObjectRogueApAlarmDetails(self):
        """
        Test RogueAccessPointAlarmObjectRogueApAlarmDetails
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.rogue_access_point_alarm_object_rogue_ap_alarm_details.RogueAccessPointAlarmObjectRogueApAlarmDetails()
        pass


if __name__ == '__main__':
    unittest.main()
