# coding: utf-8

"""
    PRIMECORE_PRIMECORE-WS

    API Definition of primecore

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.metrics_object_metrics_data_x_value_property import MetricsObjectMetricsDataXValueProperty


class TestMetricsObjectMetricsDataXValueProperty(unittest.TestCase):
    """ MetricsObjectMetricsDataXValueProperty unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetricsObjectMetricsDataXValueProperty(self):
        """
        Test MetricsObjectMetricsDataXValueProperty
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.metrics_object_metrics_data_x_value_property.MetricsObjectMetricsDataXValueProperty()
        pass


if __name__ == '__main__':
    unittest.main()
