# coding: utf-8

"""
    PRIMECORE_PRIMECORE-WS

    API Definition of primecore

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_access_point_count_get(self):
        """
        Test case for access_point_count_get

        
        """
        pass

    def test_access_point_get(self):
        """
        Test case for access_point_get

        
        """
        pass

    def test_access_point_id_get(self):
        """
        Test case for access_point_id_get

        
        """
        pass

    def test_access_point_name_device_type_count_get(self):
        """
        Test case for access_point_name_device_type_count_get

        
        """
        pass

    def test_access_point_name_total_usernames_get(self):
        """
        Test case for access_point_name_total_usernames_get

        
        """
        pass

    def test_building_get(self):
        """
        Test case for building_get

        
        """
        pass

    def test_network_metric_building_get(self):
        """
        Test case for network_metric_building_get

        
        """
        pass

    def test_rogue_access_point_alarm_count_get(self):
        """
        Test case for rogue_access_point_alarm_count_get

        
        """
        pass

    def test_rogue_access_point_alarm_get(self):
        """
        Test case for rogue_access_point_alarm_get

        
        """
        pass

    def test_rogue_access_point_alarm_id_get(self):
        """
        Test case for rogue_access_point_alarm_id_get

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
