# coding: utf-8

"""
    PRIMECORE_PRIMECORE-WS

    API Definition of primecore

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.metrics_object import MetricsObject


class TestMetricsObject(unittest.TestCase):
    """ MetricsObject unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetricsObject(self):
        """
        Test MetricsObject
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.metrics_object.MetricsObject()
        pass


if __name__ == '__main__':
    unittest.main()
