# coding: utf-8

"""
    PRIMECORE_PRIMECORE-WS

    API Definition of primecore

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.inline_response_200_2_device_type_counts import InlineResponse2002DeviceTypeCounts


class TestInlineResponse2002DeviceTypeCounts(unittest.TestCase):
    """ InlineResponse2002DeviceTypeCounts unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2002DeviceTypeCounts(self):
        """
        Test InlineResponse2002DeviceTypeCounts
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.inline_response_200_2_device_type_counts.InlineResponse2002DeviceTypeCounts()
        pass


if __name__ == '__main__':
    unittest.main()
